[package]
name = "ldpc-codes"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Библиотека для двоичных LDPC-кодов"

[dependencies]
gf-linalg = { path = "../gf-linalg", version = "0.1.0" }
gfpm = { path = "../gfpm", version = "1.0.0" }

[lib]
name = "ldpc_codes"
path = "src/lib.rs"
